
<h1><font color = 'red' size = '5'>
<b>
Exercise 1: Splitting, Applying and Combining Data Sources
</b>
</font>
</h1>

We will study a handy method the **groupby** method, which provides a quick method for selecting groups of data at a time and provides additional functionality through the **DataFrameGroupBy** object.

1. Open a new Jupyter or colab notebook.

2. Use **pandas** to load the Titanic dataset:

In [15]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv('/content/drive/MyDrive/Machine Learning Lectures/datasets/titanic.csv')

In [17]:
df.head(5)

,Unnamed: 0,Cabin,Embarked,Fare,Pclass,Ticket,Age,Name,Parch,Sex,SibSp,Survived
0,0,NaN,S,7.2500,3,A/5 21171,22.0,"Braund, Mr. Owen Harris",0,male,1,0.0
1,1,C85,C,71.2833,1,PC 17599,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,female,1,1.0
2,2,NaN,S,7.9250,3,STON/O2. 3101282,26.0,"Heikkinen, Miss. Laina",0,female,0,1.0
3,3,C123,S,53.1000,1,113803,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,female,1,1.0
4,4,NaN,S,8.0500,3,373450,35.0,"Allen, Mr. William Henry",0,male,0,0.0

3. Use the **groupby** method to group the data under the **Embarked** column to find out how many different values for **Embarked** there are:

In [18]:
embarked_grouped = df.groupby('Embarked')
print(f'There are {len(embarked_grouped)} Embarked group')

There are 3 Embarked group

4. Display the output of **embarked_grouped.groups** to find what the **groupby** method actually does:

In [19]:
embarked_grouped.groups

{'C': [1, 9, 19, 26, 30, 31, 34, 36, 39, 42, 43, 48, 52, 54, 57, 60, 64, 65, 73, 96, 97, 111, 114, 118, 122, 125, 128, 130, 135, 139, 140, 155, 174, 177, 181, 194, 195, 203, 207, 209, 215, 218, 240, 244, 255, 256, 258, 273, 285, 291, 292, 295, 296, 299, 306, 307, 308, 309, 310, 311, 319, 325, 329, 337, 352, 354, 361, 362, 366, 367, 369, 370, 373, 375, 377, 378, 380, 381, 389, 393, 420, 448, 452, 453, 455, 469, 473, 484, 487, 493, 495, 496, 505, 513, 522, 523, 524, 531, 532, 533, ...], 'Q': [5, 16, 22, 28, 32, 44, 46, 47, 82, 109, 116, 126, 143, 156, 171, 186, 188, 196, 198, 208, 214, 241, 245, 260, 264, 274, 278, 280, 289, 300, 301, 303, 322, 330, 358, 359, 364, 368, 388, 411, 412, 421, 428, 459, 468, 501, 502, 510, 517, 525, 552, 560, 573, 593, 612, 613, 626, 629, 653, 654, 657, 680, 697, 703, 718, 727, 749, 767, 768, 776, 778, 787, 790, 825, 828, 885, 890, 891, 893, 897, 907, 938, 946, 954, 957, 961, 970, 975, 977, 979, 993, 997, 998, 1002, 1004, 1012, 1015, 1018, 1051, 1074, ...], 'S': [0, 2, 3, 4, 6, 7, 8, 10, 11, 12, 13, 14, 15, 17, 18, 20, 21, 23, 24, 25, 27, 29, 33, 35, 37, 38, 40, 41, 45, 49, 50, 51, 53, 55, 56, 58, 59, 62, 63, 66, 67, 68, 69, 70, 71, 72, 74, 75, 76, 77, 78, 79, 80, 81, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 110, 112, 113, 115, 117, 119, 120, 121, 123, 124, 127, 129, 131, 132, 133, 134, 136, 137, 138, 141, 142, 144, ...]}

5. Use the **iloc** method to inspect row 1 and confirm that it belongs to embarked group **C**:

In [20]:
df.iloc[1]

Unnamed: 0                                                    1
Cabin                                                       C85
Embarked                                                      C
Fare                                                    71.2833
Pclass                                                        1
Ticket                                                 PC 17599
Age                                                        38.0
Name          Cumings, Mrs. John Bradley (Florence Briggs Th...
Parch                                                         0
Sex                                                      female
SibSp                                                         1
Survived                                                    1.0
Name: 1, dtype: object

6. As the groups are a dictionary, we can iterate through them and execute
computations on the individual groups. Compute the mean age for each group,
as shown here:

In [21]:
for name, group in embarked_grouped:
  print(name, group.Age.mean())

C 32.33216981132075
Q 28.63
S 29.245204603580564

7. Another option is to use the **aggregate** method, or **agg** for short, and provide it with the function to apply across the columns. Use the **agg** method to determine the mean of each group:

In [22]:
embarked_grouped.agg(np.mean)

<ipython-input-22-9ca2b8b45566>:1: FutureWarning: The operation <function mean at 0x7e351cd28790> failed on a column. If any error is raised, this will raise an exception in a future version of pandas. Drop these columns to avoid this warning.
  embarked_grouped.agg(np.mean)

,Unnamed: 0,Fare,Pclass,Age,Parch,SibSp,Survived
Embarked,,,,,,,
C,689.655556,62.336267,1.851852,32.332170,0.370370,0.400000,0.553571
Q,667.593496,12.409012,2.894309,28.630000,0.113821,0.341463,0.389610
S,642.095186,27.418824,2.347921,29.245205,0.426696,0.550328,0.336957

8. Define a simple function that returns the first value in the column and then pass that function through to **agg**, as an example:

In [23]:
def first_val(x):
  return x.values[0]

embarked_grouped.agg(first_val)

,Unnamed: 0,Cabin,Fare,Pclass,Ticket,Age,Name,Parch,Sex,SibSp,Survived
Embarked,,,,,,,,,,,
C,1,C85,71.2833,1,PC 17599,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,female,1,1.0
Q,5,NaN,8.4583,3,330877,NaN,"Moran, Mr. James",0,male,0,0.0
S,0,NaN,7.2500,3,A/5 21171,22.0,"Braund, Mr. Owen Harris",0,male,1,0.0


<h1><font color = 'green' size = '6'>
<b>
Exercise 2: Creating Lambda Functions
</b>
</font>
</h1>

In this exercise, we will create a **Lambda** function that returns the first value in a column and use it with **agg**.

1. Write the **first_val** function as a Lambda function, passed to **agg**:

In [24]:
embarked_grouped = df.groupby('Embarked')
embarked_grouped.agg(lambda x : x.values[0])

,Unnamed: 0,Cabin,Fare,Pclass,Ticket,Age,Name,Parch,Sex,SibSp,Survived
Embarked,,,,,,,,,,,
C,1,C85,71.2833,1,PC 17599,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,female,1,1.0
Q,5,NaN,8.4583,3,330877,NaN,"Moran, Mr. James",0,male,0,0.0
S,0,NaN,7.2500,3,A/5 21171,22.0,"Braund, Mr. Owen Harris",0,male,1,0.0

2. We can also pass multiple functions to **agg** via a list to apply the functions across the dataset. Pass the Lambda function as well as the NumPy mean and standard deviation functions, like this:

In [25]:
embarked_grouped.agg([lambda x : x.values[0], np.mean, np.std])

<ipython-input-25-c9a5d2a2c89b>:1: FutureWarning: ['Cabin', 'Ticket', 'Name', 'Sex'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  embarked_grouped.agg([lambda x : x.values[0], np.mean, np.std])

         Unnamed: 0                               Fare                        \
         <lambda_0>        mean         std <lambda_0>       mean        std
Embarked
C                 1  689.655556  383.355741    71.2833  62.336267  84.185996
Q                 5  667.593496  390.418813     8.4583  12.409012  13.616133
S                 0  642.095186  374.290951     7.2500  27.418824  37.096402

             Pclass                            Age  ...                 Parch  \
         <lambda_0>      mean       std <lambda_0>  ...        std <lambda_0>
Embarked                                            ...
C                 1  1.851852  0.936802       38.0  ...  15.258092          0
Q                 3  2.894309  0.380099        NaN  ...  15.045784          0
S                 3  2.347921  0.784126       22.0  ...  14.047507          0

                                  SibSp                       Survived  \
              mean       std <lambda_0>      mean       std <lambda_0>
Embarked
C         0.370370  0.670579          1  0.400000  0.554803        1.0
Q         0.113821  0.531056          0  0.341463  0.885487        0.0
S         0.426696  0.943989          1  0.550328  1.161723        0.0


              mean       std
Embarked
C         0.553571  0.498608
Q         0.389610  0.490860
S         0.336957  0.473037

[3 rows x 21 columns]

3. Apply **numpy.sum** to the **Fare** column and the Lambda function to the **Age** column by passing **agg** a dictionary where the keys are the columns to apply the function to, and the values are the functions themselves to be able to apply different functions to different columns in the DataFrame:

In [26]:
embarked_grouped.agg({
                      'Fare' : np.sum,
                      'Age' : lambda x : x.values[0]
                     })

                Fare   Age
Embarked
C         16830.7922  38.0
Q          1526.3085   NaN
S         25033.3862  22.0

4. Finally, execute the **groupby** method using more than one column. Provide the method with a list of the columns (**Sex** and **Embarked**) to **groupby**, like this:

In [27]:
age_embarked_grouped = df.groupby(['Sex', 'Embarked'])
age_embarked_grouped.groups

{('female', 'C'): [1, 9, 19, 31, 39, 43, 52, 111, 114, 128, 140, 177, 194, 195, 215, 218, 240, 255, 256, 258, 291, 299, 306, 307, 309, 310, 311, 319, 325, 329, 337, 362, 366, 367, 369, 375, 380, 381, 389, 393, 448, 469, 473, 496, 513, 523, 533, 537, 539, 556, 578, 581, 591, 608, 641, 644, 691, 700, 702, 710, 716, 742, 780, 830, 835, 842, 849, 852, 858, 866, 874, 875, 879, 899, 906, 910, 915, 917, 939, 950, 965, 991, 995, 1003, 1013, 1041, 1059, 1070, 1075, 1099, 1109, 1111, 1115, 1116, 1130, 1131, 1140, 1163, 1174, 1187, ...], ('female', 'Q'): [22, 28, 32, 44, 47, 82, 109, 156, 186, 198, 208, 241, 264, 274, 289, 300, 303, 322, 330, 358, 359, 368, 412, 501, 502, 573, 593, 612, 653, 654, 657, 680, 697, 727, 767, 885, 897, 954, 957, 961, 970, 977, 979, 1002, 1004, 1018, 1051, 1091, 1097, 1107, 1118, 1164, 1173, 1182, 1195, 1204, 1206, 1299, 1301, 1302], ('female', 'S'): [2, 3, 8, 10, 11, 14, 15, 18, 24, 25, 38, 40, 41, 49, 53, 56, 58, 66, 68, 71, 79, 84, 85, 88, 98, 100, 106, 113, 119, 123, 132, 133, 136, 141, 142, 147, 151, 161, 166, 167, 172, 180, 184, 190, 192, 199, 205, 211, 216, 229, 230, 233, 235, 237, 246, 247, 251, 254, 257, 259, 268, 269, 272, 275, 276, 279, 290, 293, 297, 312, 315, 316, 318, 323, 327, 328, 334, 341, 345, 346, 347, 356, 357, 374, 376, 383, 387, 394, 396, 399, 402, 404, 409, 415, 416, 417, 419, 423, 426, 427, ...], ('female', nan): [61, 829], ('male', 'C'): [26, 30, 34, 36, 42, 48, 54, 57, 60, 64, 65, 73, 96, 97, 118, 122, 125, 130, 135, 139, 155, 174, 181, 203, 207, 209, 244, 273, 285, 292, 295, 296, 308, 352, 354, 361, 370, 373, 377, 378, 420, 452, 453, 455, 484, 487, 493, 495, 505, 522, 524, 531, 532, 544, 547, 550, 553, 557, 568, 583, 584, 587, 598, 599, 604, 620, 622, 632, 645, 647, 659, 661, 679, 681, 685, 693, 698, 709, 731, 737, 762, 766, 773, 789, 793, 798, 803, 817, 827, 832, 839, 843, 847, 859, 889, 908, 911, 914, 918, 920, ...], ('male', 'Q'): [5, 16, 46, 116, 126, 143, 171, 188, 196, 214, 245, 260, 278, 280, 301, 364, 388, 411, 421, 428, 459, 468, 510, 517, 525, 552, 560, 613, 626, 629, 703, 718, 749, 768, 776, 778, 787, 790, 825, 828, 890, 891, 893, 907, 938, 946, 975, 993, 997, 998, 1012, 1015, 1074, 1084, 1124, 1147, 1162, 1249, 1271, 1272, 1279, 1287, 1290], ('male', 'S'): [0, 4, 6, 7, 12, 13, 17, 20, 21, 23, 27, 29, 33, 35, 37, 45, 50, 51, 55, 59, 62, 63, 67, 69, 70, 72, 74, 75, 76, 77, 78, 80, 81, 83, 86, 87, 89, 90, 91, 92, 93, 94, 95, 99, 101, 102, 103, 104, 105, 107, 108, 110, 112, 115, 117, 120, 121, 124, 127, 129, 131, 134, 137, 138, 144, 145, 146, 148, 149, 150, 152, 153, 154, 157, 158, 159, 160, 162, 163, 164, 165, 168, 169, 170, 173, 175, 176, 178, 179, 182, 183, 185, 187, 189, 191, 193, 197, 200, 201, 202, ...]}